# Matrix eigendecomposition

For a given 2x2 matrix:

In [2]:
# Contributed by Yannik Suhre
#### imports ####
import numpy as np

In [3]:
# define the matrix
A = np.matrix("1 3; 2 2")
print("A: \n", A)

A: 
 [[1 3]
 [2 2]]


In [4]:
# get the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

In [5]:
# Show values
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:  [-1.  4.]
Eigenvectors:
 [[-0.83205029 -0.70710678]
 [ 0.5547002  -0.70710678]]


In [5]:
# create the diagonal matrix of \Lambda
Lambda = np.diag(eigenvalues)
print(Lambda)

[[ 7.63324958  0.        ]
 [ 0.         -5.63324958]]


In [6]:
# create S the matrix of eigenvectors
S = eigenvectors
print(S)

[[ 0.83525687 -0.35209031]
 [ 0.54985995  0.93596603]]


In [7]:
# check and confirm the decomposition
A_ = np.matmul(np.matmul(S,Lambda), np.linalg.inv(S))
print("Computing A with decomposed elements:\n", A_)

Computing A with decomposed elements:
 [[ 5.  4.]
 [ 7. -3.]]


For a random matrix:

In [8]:
# define a random square matrix
N = 4
A = np.random.randint(10, size=(N, N))
print("A: \n", A)

A: 
 [[2 5 1 3]
 [3 0 8 7]
 [0 4 8 6]
 [9 9 1 0]]


In [9]:
# Eigendecomposition
eigenvalues, eigenvectors = np.linalg.eig(A)

In [10]:
# Show values
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [16.82529884  3.50989325 -3.55795783 -6.77723427]
Eigenvectors:
 [[-0.3250812   0.39717524 -0.60238306  0.15606045]
 [-0.5458321  -0.09103172  0.44710622 -0.67894007]
 [-0.58786915 -0.70100399 -0.41990162 -0.10441087]
 [-0.50079876  0.58528494  0.51079673  0.70977735]]


In [11]:
# create the diagonal matrix of \Lambda
Lambda = np.diag(eigenvalues)
print(Lambda)

[[16.82529884  0.          0.          0.        ]
 [ 0.          3.50989325  0.          0.        ]
 [ 0.          0.         -3.55795783  0.        ]
 [ 0.          0.          0.         -6.77723427]]


In [12]:
# create S the matrix of eigenvectors
S = eigenvectors
print(S)

[[-0.3250812   0.39717524 -0.60238306  0.15606045]
 [-0.5458321  -0.09103172  0.44710622 -0.67894007]
 [-0.58786915 -0.70100399 -0.41990162 -0.10441087]
 [-0.50079876  0.58528494  0.51079673  0.70977735]]


In [13]:
# check and confirm the decomposition
A_ = np.matmul(np.matmul(S,Lambda), np.linalg.inv(S))
print("Computing A with decomposed elements:\n", A_)

Computing A with decomposed elements:
 [[ 2.00000000e+00  5.00000000e+00  1.00000000e+00  3.00000000e+00]
 [ 3.00000000e+00 -2.72685832e-15  8.00000000e+00  7.00000000e+00]
 [ 5.71524084e-15  4.00000000e+00  8.00000000e+00  6.00000000e+00]
 [ 9.00000000e+00  9.00000000e+00  1.00000000e+00 -1.80199101e-15]]
