In [1]:
# Cooperation: Jan and Yannik
import numpy as np
import math
import scipy.linalg
from sympy import Matrix

In [2]:
# define a random square matrix
N = 3
A = np.random.randint(4, size=(N, N))
print("A: \n", A)

A: 
 [[1 3 2]
 [3 3 3]
 [2 3 2]]


One precondition for $det(e^\underline{\underline{A}})=e^{tr(\underline{\underline{A}})}$ to hold, is that the matrix $\underline{\underline{A}}$ is diagonalizable, meaning non-defective. Lets check this.

In [3]:
if Matrix(A).is_diagonalizable():
    print("Matrix A is diagonalizable!")
else:
    raise(NameError("Matrix A is not diagonalizable!"))

Matrix A is diagonalizable!


Let us check out how long it does in average take to calculate $e^{tr(\underline{\underline{A}})}$.

In [4]:
%%timeit
math.e**np.trace(A)

6.69 µs ± 188 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Next how long it does take to calculate $det(e^{\underline{\underline{A}}})$.

In [5]:
%%timeit
np.linalg.det(scipy.linalg.expm(A))

297 µs ± 4.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


As we can see, it takes, for this use case, around 50 times as long to calculate the $det(e^\underline{\underline{A}})$.

Lastly, let us check, whether both numbers are the same.

In [7]:
round(math.e**np.trace(A), 4) == round(np.linalg.det(scipy.linalg.expm(A)), 4)

True

They are the same. So, we numerically demonstrated, that $det(e^\underline{\underline{A}})=e^{tr(\underline{\underline{A}})}$.