In [1]:
# Vectors & Matrices & Products
# Jan Nagler
import sympy as sympy
import numpy as np
from scipy import *
import cmath as cmath
import matplotlib.pyplot as plt

In [2]:
A=array([[1,2],[3,4],[5,6]])

In [3]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
B=np.transpose(A)

In [5]:
B

array([[1, 3, 5],
       [2, 4, 6]])

In [6]:
A=array([[1,2],[3,4]])
B=np.transpose(A)

In [7]:
A

array([[1, 2],
       [3, 4]])

In [8]:
B

array([[1, 3],
       [2, 4]])

In [9]:
from numpy import dot

In [10]:
C = np.dot(A,B)

In [11]:
C

array([[ 5, 11],
       [11, 25]])

In [12]:
Inv=np.linalg.inv(A)

In [13]:
C = np.dot(A,Inv)

In [14]:
C

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [15]:
def dotproduct( v1, v2 ):
    d = 0
    if len(v1) != len(v2): print ("nasty"); return
    else:
        for i in range(0,len(v1)):
            d = d + v1[i]*v2[i]
    return d

In [16]:
u=array([1,2,3])
v=array([10,2,3])

In [17]:
print(dotproduct(u,v))
print(np.dot(u,v)) 

23
23
